{% set version = "0.9" %}
{% set name = "py-sirius-ms" %}
{% set commit = "5064de70794ce0b28ace80f33e536c7a374c56f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boecker-lab/sirius-client-openAPI/archive/{{ commit }}.zip
  sha256: 84f19f6a48ea510c040642c5e81e2a1b3e3a0a1fe0823900241ea797306a04b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./client-api_python/generated -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - certifi >=14.05.14
    - six >=1.10
    - python-dateutil >=2.5.3
    - setuptools >=21.0.0
    - urllib3 >=1.15.1
    - sirius-ms >=5.7.0

test:
  imports:
    - PySirius
  requires:
    - pip
    - openjdk
  commands:
    - pip check
    - sh $RECIPE_DIR/test_script.sh           # [not win]
    - call %RECIPE_DIR%/test_script.bat        # [win]

about:
  home: https://github.com/boecker-lab/sirius-client-openAPI/tree/master/client-api_python
  summary: 'PySirius: Python library for SIRIUS MS/MS analyses software.'
  description: |
    Python client for the SIRIUS (local) REST API (OpenAPI) that provides the full functionality of the SIRIUS 
    MS/MS analyses software including its web based features as background service.
  license: Apache-2.0
  license_file: client-api_python/LICENSE.txt
  doc_url: https://boecker-lab.github.io/docs.sirius.github.io/
  dev_url: https://github.com/boecker-lab/sirius-client-openAPI/tree/master/client-api_python

extra:
  recipe-maintainers:
    - joXemMx
    - mfleisch
    - LukasScholz
