{% set version = "3.0+sirius6.1.0" %}
{% set name = "py-sirius-ms" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boecker-lab/sirius-client-openAPI/archive/refs/tags/{{ version }}.zip
  sha256: 46e8a364c23bd6c64ff0627cb72c0c955322f5f365d418e49dfdd175263fe764

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./client-api_python/generated -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=21.0.0
  run:
    - python >=3.8
    - certifi >=14.05.14
    - six >=1.10
    - python-dateutil >=2.5.3
    - urllib3 >=1.25.3, <2.1.0
    - typing-extensions >=4.7.1
    - pydantic >=2
    - sirius-ms >=6.1.0

test:
  imports:
    - PySirius
  requires:
    - pip
    - openjdk
  commands:
    - pip check
    - sh $RECIPE_DIR/test_script.sh           # [not win]
    - call %RECIPE_DIR%/test_script.bat        # [win]

about:
  home: https://github.com/boecker-lab/sirius-client-openAPI/tree/master/client-api_python
  summary: 'PySirius: Python library for SIRIUS MS/MS analyses software.'
  description: |
    Python client for the SIRIUS (local) REST API (OpenAPI) that provides the full functionality of the SIRIUS 
    MS/MS analyses software including its web based features as background service.
  license: Apache-2.0
  license_file: client-api_python/LICENSE.txt
  doc_url: https://v6.docs.sirius-ms.io/
  dev_url: https://github.com/sirius-ms/sirius-client-openAPI/tree/master/client-api_python

extra:
  recipe-maintainers:
    - joXemMx
    - mfleisch
