{% set version = "3.1+sirius6.3.3" %}
{% set name = "py-sirius-ms" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boecker-lab/sirius-client-openAPI/archive/refs/tags/{{ version }}.zip
  sha256: 88de1c6d724d9e69dd834a46bfefad65b45795e23f7f6d3a4907624cc6c52a56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./client-api_python/generated -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=21.0.0
  run:
    - python >={{ python_min }}
    - sirius-ms >=6.3.3
    - urllib3 >=2.1.0, <3.0.0
    - python-dateutil >=2.8.2
    - pydantic >=2
    - typing-extensions >=4.7.1
test:
  imports:
    - PySirius
  requires:
    - pip
    - openjdk
  commands:
    - pip check
    - sh $RECIPE_DIR/test_script.sh           # [not win]
    - call %RECIPE_DIR%/test_script.bat        # [win]

about:
  home: https://github.com/boecker-lab/sirius-client-openAPI/tree/master/client-api_python
  summary: 'PySirius: Python library for SIRIUS MS/MS analyses software.'
  description: |
    Python client for the SIRIUS (local) REST API (OpenAPI) that provides the full functionality of the SIRIUS 
    MS/MS analyses software including its web based features as background service.
  license: Apache-2.0
  license_file: client-api_python/LICENSE.txt
  doc_url: https://v6.docs.sirius-ms.io/
  dev_url: https://github.com/sirius-ms/sirius-client-openAPI/tree/master/client-api_python

extra:
  recipe-maintainers:
    - joXemMx
    - mfleisch
